### ISSUE TITLE
Links to old class component examples on Scrimba

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/react-hooks-lecture-videos-import-export#1]
### Canvas Link

https://learning.flatironschool.com/courses/5221/pages/video-import-slash-export-and-code-organization?module_item_id=448530

### Concern

Links to old Scrimba vid using class-based components confusing students.

### Suggested Changes

Should update to link to Functional example here https://scrimba.com/scrim/crqgg7fM?pl=pzvM7hM

**Comment by jlboba** [comment]
Thank you for raising this issue, it has been fixed!
