### ISSUE TITLE
I can't play video 

### ISSUE THREAD

**Issue by asti2020** [learn-co-curriculum/react-hooks-lecture-videos-import-export#3]
### Canvas Link

I https://learning.flatironschool.com/courses/5228/pages/video-import-slash-export-and-code-organization?module_item_id=479328

### Concern

Login not working!  
I am unable to watch the video!!

**Comment by lizbur10** [comment]
Hi @asti2020 ! Thanks for bringing this to our attention. The issue should now be resolved but please let us know if you're continuing to have problems. 💙
